<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field firstname required">
            <label class="label" for="firstname"><span><?php /* @escapeNotVerified */ echo __('Voornaam') ?></span></label>
            <div class="control">
                <input name="firstname" id="firstname" title="<?php /* @escapeNotVerified */ echo __('firstname') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>


        <div class="field lastname required">
            <label class="label" for="lastname"><span><?php /* @escapeNotVerified */ echo __('Achternaam') ?></span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>


        <div class="field email required">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>


        <div class="field sector required">
            <label class="label" for="sector"><span><?php /* @escapeNotVerified */ echo __('Welke sector spreekt je nu het meest aan?') ?></span></label>
            <div class="control">
                <input name="sector" id="sector" title="<?php /* @escapeNotVerified */ echo __('ecommerce') ?>" value="ecommerce" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }"  checked />E-commerce<br />
                 <input name="sector" id="sector" title="<?php /* @escapeNotVerified */ echo __('hosting') ?>" value="hosting" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />Hosting<br />
                  <input name="sector" id="sector" title="<?php /* @escapeNotVerified */ echo __('marketingbureau') ?>" value="marketingbureau" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />Marketingbureau<br />
                 <input name="sector" id="sector" title="<?php /* @escapeNotVerified */ echo __('gaming') ?>" value="gaming" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />Gaming<br />
                 <input name="sector" id="sector" title="<?php /* @escapeNotVerified */ echo __('softwarehuis') ?>" value="softwarehuis" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />Softwarehuis<br />
                  <input name="sector" id="sector" title="<?php /* @escapeNotVerified */ echo __('appdev') ?>" value="appdev" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />Web App development<br />
         </div>
        </div>


          <div class="field direction required">
            <label class="label" for="direction"><span><?php /* @escapeNotVerified */ echo __('Welke richting spreekt je nu het meest aan?') ?></span></label>
            <div class="control">
                <input name="direction" id="direction" title="<?php /* @escapeNotVerified */ echo __('frontend') ?>" value="frontend" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }"  checked/>Frontend<br />
                 <input name="direction" id="direction" title="<?php /* @escapeNotVerified */ echo __('backend') ?>" value="backend" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />Backend<br />
                  <input name="direction" id="direction" title="<?php /* @escapeNotVerified */ echo __('devops') ?>" value="devops" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />DevOps<br />
         </div>
        </div>


       <div class="field pace required">
            <label class="label" for="pace"><span><?php /* @escapeNotVerified */ echo __('Wat vindt je van de snelheid van het lesgeven?') ?></span></label>
            <div class="control">
                <input name="pace" id="pace" title="<?php /* @escapeNotVerified */ echo __('1') ?>" value="1" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" checked />1<br />
                 <input name="pace" id="pace" title="<?php /* @escapeNotVerified */ echo __('2') ?>" value="2" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />2<br />
                  <input name="pace" id="pace" title="<?php /* @escapeNotVerified */ echo __('3') ?>" value="3" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />3<br />
                 <input name="pace" id="pace" title="<?php /* @escapeNotVerified */ echo __('4') ?>" value="4" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />4<br />
                 <input name="pace" id="pace" title="<?php /* @escapeNotVerified */ echo __('5') ?>" value="5" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />5<br />
                  <input name="pace" id="pace" title="<?php /* @escapeNotVerified */ echo __('6') ?>" value="6" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />6<br />
         </div>
        </div>


       <div class="field materials required">
            <label class="label" for="materials"><span><?php /* @escapeNotVerified */ echo __('Wat vond je van de aangeboden stof?') ?></span></label>
            <div class="control">
                <input name="materials" id="materials" title="<?php /* @escapeNotVerified */ echo __('1') ?>" value="1" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" checked />1<br />
                 <input name="materials" id="materials" title="<?php /* @escapeNotVerified */ echo __('2') ?>" value="2" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />2<br />
                  <input name="materials" id="materials" title="<?php /* @escapeNotVerified */ echo __('3') ?>" value="3" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />3<br />
                 <input name="materials" id="materials" title="<?php /* @escapeNotVerified */ echo __('4') ?>" value="4" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />4<br />
                 <input name="materials" id="materials" title="<?php /* @escapeNotVerified */ echo __('5') ?>" value="5" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />5<br />
                  <input name="materials" id="materials" title="<?php /* @escapeNotVerified */ echo __('6') ?>" value="6" class="radio" type="radio" data-validate="{required:true, 'validate-one-required-by-name':true }" />6<br />
         </div>
        </div>


        <div class="field understood required">
            <label class="label" for="understood"><span><?php /* @escapeNotVerified */ echo __('Is er iets wat je niet goed hebt begrepen?') ?></span></label>
            <div class="control">
                <input name="understood" id="understood" title="<?php /* @escapeNotVerified */ echo __('understood') ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>


        <div class="field help_asked required">
            <label class="label" for="help_asked"><span><?php /* @escapeNotVerified */ echo __('Heb je hulp gevraagd aan een van je mede bootcampers?') ?></span></label>
            <div class="control">
                <input name="help_asked" id="help_asked" title="<?php /* @escapeNotVerified */ echo __('help_asked') ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>


        <div class="field helper required">
            <label class="label" for="helper"><span><?php /* @escapeNotVerified */ echo __('Zo ja, wie was het meest behulpzaam?') ?></span></label>
            <div class="control">
                <input name="helper" id="helper" title="<?php /* @escapeNotVerified */ echo __('helper') ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>



       <div class="field questions required">
            <label class="label" for="questions"><span><?php /* @escapeNotVerified */ echo __('Verdere opmerkingen?') ?></span></label>
            <div class="control">
                <textarea name="questions" id="questions" title="<?php /* @escapeNotVerified */ echo __('Verdere opmerkingen?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
